apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: inod-smailandstuff
spec:
  environments:
    - name: production
      build:
        from: master
  components:
    - name: webapp
      src: .
      ports:
       - name: http
         port: 3000
      public: true
      replicas: 1
      environmentConfig:
        - environment: production
          variables:
            TENANTID: "3aa4a235-b6e2-48d5-9195-7fcf05b459b0"
            CLIENTID: "4715194e-2037-45ad-bdd7-c1c92a459475"
            NODE_ENV: "development"
      secrets:
        - CLIENTSECRET
